# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'IronSourceDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'IronSourceSDK', '~> 7.2.1.1'
  pod 'StartAppSDK', '~> 4.7.0'
  pod 'startio-ironsource-mediation', :path => '../'

end
